name: Build
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Install node dependencies via yarn
        run: yarn install
      - name: Test
        run: CI=true yarn dlx --package firebase-tools firebase emulators:exec --only firestore "yarn test"

  typescript:
    name: TypeScript Compiler type check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Install node dependencies via yarn
        run: yarn install
      - name: TypeScript compiler
        run: make verify-typescript

  deploy:
    if: github.ref == 'refs/heads/main'
    concurrency: firebase_deploy
    name: Deploy
    needs: [build, test, typescript]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          args: deploy -f
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
